<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="MovieReviews.AspNet.BackEnd._Default" %>
<%@ Register TagPrefix="ds" Namespace="Linq2DynamoDb.AspNet.DataSource" Assembly="Linq2DynamoDb.AspNet.DataSource" %>

<asp:Content runat="server" ID="FeaturedContent" ContentPlaceHolderID="FeaturedContent">
    <section class="featured">
        <div class="content-wrapper">
    
        <asp:Button ID="Button1" runat="server" Text="Add" OnClick="Button1_Click" />
        <asp:Button ID="Button2" runat="server" Text="Test" OnClick="Button2_Click" />

        </div>
    </section>
</asp:Content>
<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    
        <asp:GridView 
            ID="GridView1" 
            runat="server" 
            DataSourceID="MyDataSource1" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            ShowFooter="True"
            AllowSorting="True"
            AllowPaging="True" PagerSettings-Position="TopAndBottom" PagerSettings-Mode="NumericFirstLast" PagerSettings-PageButtonCount="10">
        </asp:GridView>

        <ds:DynamoDbDataSource 
            ID="MyDataSource1" 
            runat="server" 
            ContextTypeName="MovieReviews.DataModel.ReviewsDataContext" 
            TableName="Movies" 
            GenerateEmptyRowOnTop="False"
         >
         </ds:DynamoDbDataSource>
        
</asp:Content>
